export enum MemorySource {
  SOURCE_CODE = 'SOURCE_CODE',
  SYMBOL_GRAPH = 'SYMBOL_GRAPH',
  DEPENDENCY_GRAPH = 'DEPENDENCY_GRAPH',
  ARCHITECTURE_ANALYSIS = 'ARCHITECTURE_ANALYSIS',
  TASK_EXECUTION = 'TASK_EXECUTION',
  TEST_RESULT = 'TEST_RESULT',
  BUILD_RESULT = 'BUILD_RESULT',
  RECOVERY = 'RECOVERY',
  USER_DECISION = 'USER_DECISION',
  SLM_INFERENCE = 'SLM_INFERENCE'
}
