export enum Outcome {
  SUCCESS = 'SUCCESS',
  PARTIAL_SUCCESS = 'PARTIAL_SUCCESS',
  FAILED = 'FAILED',
  ABANDONED = 'ABANDONED',
  BLOCKED = 'BLOCKED',
  CANCELLED = 'CANCELLED',
  UNKNOWN = 'UNKNOWN'
}
