export enum UncertaintyType {
  TASK_AMBIGUITY = 'TASK_AMBIGUITY',
  FEATURE_AMBIGUITY = 'FEATURE_AMBIGUITY',
  ENTITY_AMBIGUITY = 'ENTITY_AMBIGUITY',
  KNOWLEDGE_GAP = 'KNOWLEDGE_GAP',
  CONTRADICTORY_KNOWLEDGE = 'CONTRADICTORY_KNOWLEDGE',
  STALE_KNOWLEDGE = 'STALE_KNOWLEDGE',
  LOW_CONFIDENCE = 'LOW_CONFIDENCE',
  MULTIPLE_VALID_PATHS = 'MULTIPLE_VALID_PATHS',
  INSUFFICIENT_EVIDENCE = 'INSUFFICIENT_EVIDENCE',
  NONE = 'NONE'
}
