export enum SecurityEventType {
  ACTION_EVALUATED = 'ACTION_EVALUATED',
  ACTION_ALLOWED = 'ACTION_ALLOWED',
  ACTION_APPROVAL_REQUIRED = 'ACTION_APPROVAL_REQUIRED',
  ACTION_DENIED = 'ACTION_DENIED',
  POLICY_MATCHED = 'POLICY_MATCHED',
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  PROTECTED_RESOURCE_ACCESS = 'PROTECTED_RESOURCE_ACCESS'
}
