export enum AgentPermission {
  READ_REPOSITORY = 'READ_REPOSITORY',
  WRITE_REPOSITORY = 'WRITE_REPOSITORY',
  CREATE_FILES = 'CREATE_FILES',
  DELETE_FILES = 'DELETE_FILES',
  RUN_TESTS = 'RUN_TESTS',
  RUN_BUILD = 'RUN_BUILD',
  RUN_LINT = 'RUN_LINT',
  RUN_TYPECHECK = 'RUN_TYPECHECK',
  GIT_READ = 'GIT_READ',
  GIT_WRITE = 'GIT_WRITE',
  NETWORK_ACCESS = 'NETWORK_ACCESS',
  PLUGIN_EXECUTION = 'PLUGIN_EXECUTION'
}
