export type HealthSignalType =
  // Complexity
  | 'HIGH_CYCLOMATIC_COMPLEXITY'
  | 'HIGH_COGNITIVE_COMPLEXITY'
  | 'DEEP_NESTING'
  | 'LARGE_FILE_SIZE'
  | 'LARGE_METHOD_SIZE'
  | 'HIGH_FLOW_COMPLEXITY'
  | 'HIGH_BRANCH_COMPLEXITY'
  | 'HIGH_BEHAVIOR_VARIANTS'
  | 'HIGH_ERROR_PATH_COMPLEXITY'
  // Coupling & Dependency
  | 'HIGH_AFFERENT_COUPLING'
  | 'HIGH_EFFERENT_COUPLING'
  | 'TIGHT_COUPLING'
  | 'UNBALANCED_COUPLING'
  | 'CIRCULAR_FEATURE_DEPENDENCY'
  | 'CIRCULAR_DEPENDENCY'
  | 'DEPRECATED_DEPENDENCY'
  | 'OUTDATED_DEPENDENCY'
  | 'UNPINNED_DEPENDENCY'
  | 'HIDDEN_TRANSITIVE_DEPENDENCY'
  | 'EXCESSIVE_DEPENDENCIES'
  | 'HIGH_DEPENDENCY_COUNT'
  | 'HIGH_DEPENDENT_COUNT'
  | 'HIGH_CROSS_FEATURE_COUPLING'
  | 'CENTRAL_FEATURE'
  | 'SHARED_RESOURCE_PRESSURE'
  // Verification
  | 'MISSING_TESTS'
  | 'LOW_TEST_COVERAGE'
  | 'NO_INTEGRATION_TESTS'
  | 'UNTESTED_CRITICAL_FLOW'
  | 'FLAKY_TEST_HISTORY'
  | 'ASSERTION_FREE_TEST'
  | 'LOW_TEST_SUPPORT'
  | 'MISSING_TEST_SUPPORT'
  | 'WEAK_FAILURE_VERIFICATION'
  | 'LOW_BEHAVIOR_VERIFICATION'
  | 'LOW_ENTRY_POINT_VERIFICATION'
  // Behavior
  | 'COMPLEX_EXECUTION_FLOW'
  | 'DEAD_END_FLOW'
  | 'UNHANDLED_ERROR_PATH'
  | 'ASYNC_RACE_CONDITION'
  | 'UNTERMINATED_FLOW'
  | 'AMBIGUOUS_BEHAVIOR_BRANCH'
  | 'BEHAVIOR_CONFLICT'
  | 'INCOMPLETE_FLOW'
  | 'MISSING_FAILURE_FLOW'
  | 'MISSING_AUTHORIZATION_FLOW'
  | 'MISSING_VALIDATION_FLOW'
  | 'UNRESOLVED_FLOW'
  | 'LOW_BEHAVIOR_CONFIDENCE'
  // Architecture & Structure
  | 'LAYER_VIOLATION'
  | 'CROSS_DOMAIN_LEAK'
  | 'BYPASSED_ABSTRACTION'
  | 'SHARED_DATABASE_TABLE'
  | 'CIRCULAR_MODULE_REFERENCE'
  | 'ORPHAN_FEATURE_COMPONENT'
  | 'SINGLE_POINT_OF_FAILURE'
  | 'UNRESOLVED_TODO_CONCENTRATION'
  | 'HIGH_RESOURCE_COUNT'
  | 'HIGH_SYMBOL_COUNT'
  | 'HIGH_MODULE_COUNT'
  | 'HIGH_RESOURCE_CONCENTRATION'
  | 'ARCHITECTURAL_INCONSISTENCY'
  | 'LAYER_BOUNDARY_VIOLATION'
  | 'CROSS_BOUNDARY_COUPLING'
  | 'DUPLICATED_RESPONSIBILITY'
  // Stability & Change
  | 'HIGH_CHURN_RATE'
  | 'FREQUENT_BUG_FIXES'
  | 'RECENT_BREAKING_CHANGE'
  | 'HOTSPOT_DETECTED'
  | 'RAPID_SUCCESSIVE_CHANGES'
  | 'HIGH_CHANGE_FREQUENCY'
  | 'UNSTABLE_MAPPING'
  | 'UNSTABLE_BEHAVIOR'
  | 'FREQUENT_STRUCTURAL_CHANGE'
  // Integration
  | 'UNDOCUMENTED_API_ENDPOINT'
  | 'MISSING_TIMEOUT_CONFIGURATION'
  | 'MISSING_CIRCUIT_BREAKER'
  | 'UNVALIDATED_EXTERNAL_INPUT'
  | 'UNRETRYABLE_NETWORK_CALL'
  | 'EXTERNAL_SERVICE_DEPENDENCY'
  | 'SINGLE_EXTERNAL_PROVIDER'
  | 'UNVERIFIED_INTEGRATION_FAILURE'
  | 'INTEGRATION_BOUNDARY_RISK'
  // Security
  | 'EXPOSED_SECRET'
  | 'MISSING_AUTHENTICATION'
  | 'INSECURE_CONFIGURATION'
  | 'PERMISSIVE_CORS'
  | 'UNVALIDATED_INPUT'
  | 'PROMPT_INJECTION_VULNERABILITY'
  | 'SECURITY_SENSITIVE_FEATURE'
  | 'AUTHORIZATION_GAP'
  | 'VALIDATION_GAP'
  | 'SENSITIVE_BOUNDARY'
  | 'SECURITY_VERIFICATION_GAP'
  // Confidence
  | 'LOW_DISCOVERY_CONFIDENCE'
  | 'DISPUTED_RESOURCE_MAPPING'
  | 'STALE_KNOWLEDGE'
  | 'LOW_MAPPING_CONFIDENCE'
  | 'LOW_DEPENDENCY_CONFIDENCE'
  | 'CONFLICTING_EVIDENCE';

export const HEALTH_SIGNAL_TYPES: readonly HealthSignalType[] = [
  'HIGH_CYCLOMATIC_COMPLEXITY',
  'HIGH_COGNITIVE_COMPLEXITY',
  'DEEP_NESTING',
  'LARGE_FILE_SIZE',
  'LARGE_METHOD_SIZE',
  'HIGH_FLOW_COMPLEXITY',
  'HIGH_BRANCH_COMPLEXITY',
  'HIGH_BEHAVIOR_VARIANTS',
  'HIGH_ERROR_PATH_COMPLEXITY',
  'HIGH_AFFERENT_COUPLING',
  'HIGH_EFFERENT_COUPLING',
  'TIGHT_COUPLING',
  'UNBALANCED_COUPLING',
  'CIRCULAR_FEATURE_DEPENDENCY',
  'CIRCULAR_DEPENDENCY',
  'DEPRECATED_DEPENDENCY',
  'OUTDATED_DEPENDENCY',
  'UNPINNED_DEPENDENCY',
  'HIDDEN_TRANSITIVE_DEPENDENCY',
  'EXCESSIVE_DEPENDENCIES',
  'HIGH_DEPENDENCY_COUNT',
  'HIGH_DEPENDENT_COUNT',
  'HIGH_CROSS_FEATURE_COUPLING',
  'CENTRAL_FEATURE',
  'SHARED_RESOURCE_PRESSURE',
  'MISSING_TESTS',
  'LOW_TEST_COVERAGE',
  'NO_INTEGRATION_TESTS',
  'UNTESTED_CRITICAL_FLOW',
  'FLAKY_TEST_HISTORY',
  'ASSERTION_FREE_TEST',
  'LOW_TEST_SUPPORT',
  'MISSING_TEST_SUPPORT',
  'WEAK_FAILURE_VERIFICATION',
  'LOW_BEHAVIOR_VERIFICATION',
  'LOW_ENTRY_POINT_VERIFICATION',
  'COMPLEX_EXECUTION_FLOW',
  'DEAD_END_FLOW',
  'UNHANDLED_ERROR_PATH',
  'ASYNC_RACE_CONDITION',
  'UNTERMINATED_FLOW',
  'AMBIGUOUS_BEHAVIOR_BRANCH',
  'BEHAVIOR_CONFLICT',
  'INCOMPLETE_FLOW',
  'MISSING_FAILURE_FLOW',
  'MISSING_AUTHORIZATION_FLOW',
  'MISSING_VALIDATION_FLOW',
  'UNRESOLVED_FLOW',
  'LOW_BEHAVIOR_CONFIDENCE',
  'LAYER_VIOLATION',
  'CROSS_DOMAIN_LEAK',
  'BYPASSED_ABSTRACTION',
  'SHARED_DATABASE_TABLE',
  'CIRCULAR_MODULE_REFERENCE',
  'ORPHAN_FEATURE_COMPONENT',
  'SINGLE_POINT_OF_FAILURE',
  'UNRESOLVED_TODO_CONCENTRATION',
  'HIGH_RESOURCE_COUNT',
  'HIGH_SYMBOL_COUNT',
  'HIGH_MODULE_COUNT',
  'HIGH_RESOURCE_CONCENTRATION',
  'ARCHITECTURAL_INCONSISTENCY',
  'LAYER_BOUNDARY_VIOLATION',
  'CROSS_BOUNDARY_COUPLING',
  'DUPLICATED_RESPONSIBILITY',
  'HIGH_CHURN_RATE',
  'FREQUENT_BUG_FIXES',
  'RECENT_BREAKING_CHANGE',
  'HOTSPOT_DETECTED',
  'RAPID_SUCCESSIVE_CHANGES',
  'HIGH_CHANGE_FREQUENCY',
  'UNSTABLE_MAPPING',
  'UNSTABLE_BEHAVIOR',
  'FREQUENT_STRUCTURAL_CHANGE',
  'UNDOCUMENTED_API_ENDPOINT',
  'MISSING_TIMEOUT_CONFIGURATION',
  'MISSING_CIRCUIT_BREAKER',
  'UNVALIDATED_EXTERNAL_INPUT',
  'UNRETRYABLE_NETWORK_CALL',
  'EXTERNAL_SERVICE_DEPENDENCY',
  'SINGLE_EXTERNAL_PROVIDER',
  'UNVERIFIED_INTEGRATION_FAILURE',
  'INTEGRATION_BOUNDARY_RISK',
  'EXPOSED_SECRET',
  'MISSING_AUTHENTICATION',
  'INSECURE_CONFIGURATION',
  'PERMISSIVE_CORS',
  'UNVALIDATED_INPUT',
  'PROMPT_INJECTION_VULNERABILITY',
  'SECURITY_SENSITIVE_FEATURE',
  'AUTHORIZATION_GAP',
  'VALIDATION_GAP',
  'SENSITIVE_BOUNDARY',
  'SECURITY_VERIFICATION_GAP',
  'LOW_DISCOVERY_CONFIDENCE',
  'DISPUTED_RESOURCE_MAPPING',
  'STALE_KNOWLEDGE',
  'LOW_MAPPING_CONFIDENCE',
  'LOW_DEPENDENCY_CONFIDENCE',
  'CONFLICTING_EVIDENCE',
] as const;

export const VALID_HEALTH_SIGNAL_TYPES = HEALTH_SIGNAL_TYPES;

export function isHealthSignalType(type: unknown): type is HealthSignalType {
  return typeof type === 'string' && HEALTH_SIGNAL_TYPES.includes(type as HealthSignalType);
}

export const isValidHealthSignalType = isHealthSignalType;
