export enum KnowledgeErrorCode {
  KNOWLEDGE_ENTITY_NOT_FOUND = 'KNOWLEDGE_ENTITY_NOT_FOUND',
  KNOWLEDGE_REPOSITORY_NOT_FOUND = 'KNOWLEDGE_REPOSITORY_NOT_FOUND',
  KNOWLEDGE_SNAPSHOT_NOT_FOUND = 'KNOWLEDGE_SNAPSHOT_NOT_FOUND',
  KNOWLEDGE_ACCESS_DENIED = 'KNOWLEDGE_ACCESS_DENIED',
  KNOWLEDGE_QUERY_FAILED = 'KNOWLEDGE_QUERY_FAILED',
  KNOWLEDGE_VERSION_UNSUPPORTED = 'KNOWLEDGE_VERSION_UNSUPPORTED',
  KNOWLEDGE_INVALID_REQUEST = 'KNOWLEDGE_INVALID_REQUEST'
}
