export enum BrainState {
  IDLE = 'IDLE',
  UNDERSTANDING = 'UNDERSTANDING',
  QUERYING = 'QUERYING',
  ASSEMBLING_CONTEXT = 'ASSEMBLING_CONTEXT',
  REASONING = 'REASONING',
  EVALUATING = 'EVALUATING',
  DECISION_READY = 'DECISION_READY',
  PLAN_REQUESTED = 'PLAN_REQUESTED',
  CONTEXT_INSUFFICIENT = 'CONTEXT_INSUFFICIENT',
  REASONING_FAILED = 'REASONING_FAILED',
  INVALID_DECISION = 'INVALID_DECISION',
  ESCALATED = 'ESCALATED'
}
