export enum ActionType {
  // Observation
  READ_FILE = 'READ_FILE',
  READ_SYMBOL = 'READ_SYMBOL',
  SEARCH_SYMBOL = 'SEARCH_SYMBOL',
  SEARCH_TEXT = 'SEARCH_TEXT',
  GET_DEPENDENCIES = 'GET_DEPENDENCIES',
  GET_IMPACT = 'GET_IMPACT',
  GET_ARCHITECTURE = 'GET_ARCHITECTURE',

  // Modification
  CREATE_FILE = 'CREATE_FILE',
  EDIT_FILE = 'EDIT_FILE',
  DELETE_FILE = 'DELETE_FILE',
  RENAME_FILE = 'RENAME_FILE',
  MOVE_FILE = 'MOVE_FILE',

  // Verification
  RUN_TEST = 'RUN_TEST',
  RUN_LINT = 'RUN_LINT',
  RUN_TYPECHECK = 'RUN_TYPECHECK',
  RUN_BUILD = 'RUN_BUILD',

  // Repository Inspection
  GIT_STATUS = 'GIT_STATUS',
  GIT_DIFF = 'GIT_DIFF',
  GIT_CHECKPOINT = 'GIT_CHECKPOINT'
}
