export enum ContextType {
  PROJECT_OVERVIEW = 'PROJECT_OVERVIEW',
  FEATURE = 'FEATURE',
  FILE = 'FILE',
  SYMBOL = 'SYMBOL',
  DEPENDENCY = 'DEPENDENCY',
  RELATIONSHIP = 'RELATIONSHIP',
  ARCHITECTURE = 'ARCHITECTURE',
  MEMORY = 'MEMORY',
  RECENT_CHANGE = 'RECENT_CHANGE',
  KNOWN_PROBLEM = 'KNOWN_PROBLEM',
  CONFIGURATION = 'CONFIGURATION',
  TEST = 'TEST',
  DOCUMENTATION = 'DOCUMENTATION'
}
