export enum ExecutionEventType {
  EXECUTION_STARTED = 'EXECUTION_STARTED',
  ACTION_READY = 'ACTION_READY',
  ACTION_STARTED = 'ACTION_STARTED',
  ACTION_SUCCEEDED = 'ACTION_SUCCEEDED',
  ACTION_FAILED = 'ACTION_FAILED',
  ACTION_BLOCKED = 'ACTION_BLOCKED',
  ACTION_CANCELLED = 'ACTION_CANCELLED',
  EXECUTION_COMPLETED = 'EXECUTION_COMPLETED',
  EXECUTION_FAILED = 'EXECUTION_FAILED'
}
