export enum LoopStatus {
  INITIALIZING = 'INITIALIZING',
  THINKING = 'THINKING',
  PLANNING = 'PLANNING',
  AWAITING_APPROVAL = 'AWAITING_APPROVAL',
  EXECUTING = 'EXECUTING',
  VERIFYING = 'VERIFYING',
  RECOVERING = 'RECOVERING',
  LEARNING = 'LEARNING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED'
}
