export enum SLMTaskType {
  FEATURE_INTERPRETATION = 'FEATURE_INTERPRETATION',
  CONTEXT_RANKING = 'CONTEXT_RANKING',
  AMBIGUITY_RESOLUTION = 'AMBIGUITY_RESOLUTION',
  SEMANTIC_SIMILARITY = 'SEMANTIC_SIMILARITY',
  REASONING_SUMMARY = 'REASONING_SUMMARY'
}
