export enum RecoveryState {
  FAILED = 'FAILED',
  ANALYZING = 'ANALYZING',
  RECOVERY_SELECTED = 'RECOVERY_SELECTED',
  RECOVERING = 'RECOVERING',
  VERIFYING = 'VERIFYING',
  SUCCESS = 'SUCCESS',
  RETRYING = 'RETRYING',
  ROLLING_BACK = 'ROLLING_BACK',
  ROLLED_BACK = 'ROLLED_BACK',
  ESCALATED = 'ESCALATED',
  ABORTED = 'ABORTED'
}
