export enum FailureCategory {
  SYNTAX_FAILURE = 'SYNTAX_FAILURE',
  TYPE_FAILURE = 'TYPE_FAILURE',
  TEST_FAILURE = 'TEST_FAILURE',
  BUILD_FAILURE = 'BUILD_FAILURE',
  DEPENDENCY_FAILURE = 'DEPENDENCY_FAILURE',
  ARCHITECTURE_FAILURE = 'ARCHITECTURE_FAILURE',
  CONFLICT = 'CONFLICT',
  SECURITY_FAILURE = 'SECURITY_FAILURE',
  ENVIRONMENT_FAILURE = 'ENVIRONMENT_FAILURE',
  UNKNOWN_FAILURE = 'UNKNOWN_FAILURE'
}
