export enum IntentType {
  FEATURE_ADD = 'FEATURE_ADD',
  FEATURE_MODIFY = 'FEATURE_MODIFY',
  FEATURE_REMOVE = 'FEATURE_REMOVE',
  BUG_FIX = 'BUG_FIX',
  REFACTOR = 'REFACTOR',
  OPTIMIZATION = 'OPTIMIZATION',
  SECURITY_CHANGE = 'SECURITY_CHANGE',
  DEPENDENCY_UPDATE = 'DEPENDENCY_UPDATE',
  ARCHITECTURE_CHANGE = 'ARCHITECTURE_CHANGE',
  DOCUMENTATION_CHANGE = 'DOCUMENTATION_CHANGE',
  INVESTIGATION = 'INVESTIGATION',
  EXPLANATION = 'EXPLANATION',
  UNKNOWN = 'UNKNOWN'
}

export interface Intent {
  type: IntentType;
  confidence: number;
}
